version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "package.json" }}
            - v1-dependency-cache
      - run: yarn install

      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.cache/yarn

      - run: yarn validate
